version: '3.8'

services:
  # NestJS Application
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: smart-siak-api
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_DATABASE=${DB_DATABASE}
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   networks:
  #     - smart-siak-network

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: smart-siak-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-siak-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: smart-siak-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - smart-siak-network

  # PgAdmin for Database Management (Optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: smart-siak-pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@smartsiak.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - smart-siak-network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  smart-siak-network:
    driver: bridge
